#if !defined(RAPIDVULKAN_DISABLE_UNROLLED_STRUCT_METHODS) && !defined(RAPIDVULKAN_DISABLE_ARRAY_METHODS)
#include <array>
#endif
#if !defined(RAPIDVULKAN_DISABLE_UNROLLED_STRUCT_METHODS) && !defined(RAPIDVULKAN_DISABLE_VECTOR_METHODS)
#include <vector>
#endif